Editing build script to build UCNA Geant4 Code

diff --git a/scripts/install-ucna b/scripts/install-ucna
--- a/scripts/install-ucna
+++ b/scripts/install-ucna
@@ -13,12 +13,12 @@
 # 1. Environment preparation
 #
 echo "Checking that we have everything we need..."
-for CMD in cmake make tar root nproc
+for CMD in cmake make tar root nproc install
 do
 	command -v $CMD >/dev/null 2>&1 || { echo "Require $CMD but it's not installed. Aborting." >&2; exit 1; }
 done
 
-echo "Checking if the environment is setup..."
+echo "Checking if the Geant4 environment is setup..."
 if [ -z "${G4SRC}" ]; then
 	echo "Need to set G4SRC."
 	echo "Did set your genat4 install path?"
@@ -41,12 +41,14 @@ if [ -z "${G4NAME}" ]; then
 	exit 0
 fi
 
+echo "Checking if the Geant4 environment is setup..."
 if [ -z "${G4ROOT}" ]; then
 	echo "Need to set G4ROOT"
 	echo "Do you have ROOT installed?"
 	echo "Aborting install."
 	exit 1
 fi
+
 
 if [ ! -r "${G4ROOT}/FindROOT.cmake" ]; then
 	echo "${G4ROOT}/FindROOT.cmake not found."
@@ -56,9 +58,18 @@ if [ ! -r "${G4ROOT}/FindROOT.cmake" ]; then
 fi
 
 
+echo "Checking if the UCNA environment is setup..."
+if [ -z "${G4ROOT}" ]; then
+	echo "Need to set G4ROOT"
+	echo "Do you have ROOT installed?"
+	echo "Aborting install."
+	exit 1
+fi
+
+
 echo "Looks like we have everything we need."
 echo "About to build UCNA code using the following parameters." 
-echo "UCNA git repository: ${UCNAGIT}"
+#echo "UCNA git repository: ${UCNAGIT}"
 echo "Geant4 source url: ${G4URL}"
 echo "Geant4 version: ${G4NAME}"
 echo "System: ${G4SYSTEM}"
@@ -81,6 +92,11 @@ echo "Creating install directories..."
 #
 mkdir -vp ${UCNASRC}
 mkdir -vp ${UCNABIN}
+
+cd ${UCNABUILD}
+cmake -DGeant4_DIR=${G4BUILD} ${UCNASRC}/$PROGRAM
+make -j"$(nproc)"
+#install $PROGRAM ${UCNABIN}/
 
 for PROGRAM in ${UCNAEXE}
 do
